Repository hariom20singh/python-learning-codes, pull requests merged in 2022-10, with the labels that each got.

#2 Hacktoberfest 2022
  linearSearchincpp00988.cpp
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#4 added quick sort cpp code
  QuickSort.cpp
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#8 Hacktoberfest 2022
  pairwise000006.cpp
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#9 Added Selection Sort Code
  PythonDSA/SelectionSort.py
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#11 Added HACTOBERFEST.md
  HACTOBERFEST.md
Labels: hacktoberfest-accepted

#12 Added merge sort
  PythonDSA/MergeSort.py
Labels: hacktoberfest-accepted

#13 Added QuickSort in python
  PythonDSA/QuickSort.py
Labels: hacktoberfest-accepted

#14 added insertion sort in python
  PythonDSA/InsertionSort.py
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#15 Dijkstra’s Algorithm added
  PythonDSA/DijtraksAlgorithm.py
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#16 Added linked list code
  PythonDSA/linked.py
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#17 Added fibonacci series Algorithm
  PythonDSA/fibonacciSeries.py
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#23 Hacktoberfest 2022
  19.py
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#22 Hacktoberfest 2022
  15.py
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#21 Hacktoberfest 2022
  9.py
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#20 Hacktoberfest 2022
  8.py
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#19 Hacktoberfest 2022
  1.py
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#18 traversing
  PythonDSA/traversing.py
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#26 Create Pratheeksha_game
  Pratheeksha_game
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#30 Added image compression program using python
  compressed_img.jpg
  img_compress.py
  uncompressed_img.jpg
Labels: hacktoberfest-accepted

#29 Create Pratheeksha_python
  Pratheeksha_python
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#32 Mask RCNN Object detection
  RCNN object detection/RCNN demo.ipynb
  RCNN object detection/mrcnn/__init__.py
  RCNN object detection/mrcnn/config.py
  RCNN object detection/mrcnn/model.py
  RCNN object detection/mrcnn/parallel_model.py
  RCNN object detection/mrcnn/utils.py
  RCNN object detection/mrcnn/visualize.py
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#31 Added Program which displays OOPS in python
  Banking_OOPS.py
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#28 Code Added
  Numberguess.py
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#27 Added Zero Sum Subarray problem using Python
  zeroSum.py
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#35 added Doubly Linked List code
  doublyLinkedList.py
Labels: hacktoberfest-accepted

#33 added pattern problem
  diamond_pattern.py
Labels: hacktoberfest-accepted

#37 Hacktoberfest2022
  bgremover.py
Labels: hacktoberfest-accepted

#36 implemented binary tree and BFS
  PythonDSA/binary_tree.py
  PythonDSA/breadth_first_search.py
Labels: hacktoberfest-accepted

#38 Hacktoberfest 2022
  1code1020868.py
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#39 hactoberfest2022
  queue.cpp
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#40 Hactoberfest2022
  basicStack.cpp
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#44 Added Kadane Algo
  PythonDSA/KadaneAlgo.py
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#42 Hactoberfest2022
  basicDoublyLinkedlist.cpp
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#45 added cycle sort algorithm
  bucketSort.py
  cycleSort.py
  treeSort.py
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#48 added priority queue program
  PythonDSA/priorityqueue.py
  priorityqueue.py
  stack.py
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#56 Hacktoberfest 2022
  deleating_of_node.cpp
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#61 Finding a url in a string
  diamondPattern.py
  findurl.py
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#65 added binary tree insert operation in python
  PythonDSA/insert_binarytree.py
  PythonDSA/stack_using_linkedList.py
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#58 Pythagorean Triplets(DSA PYTHON))
  PythonDSA/Pythagorean Triplets(DSA PYTHON))
Labels: hacktoberfest-accepted

#60 Hectoberfest 22
  Star.py
Labels: hacktoberfest-accepted

#66 calculator.py
  calculator.ipynb
Labels: hacktoberfest-accepted

#57 added balanced_paranthesis exercise
  balanced_paranthesis.py
Labels: hacktoberfest-accepted

#68 stack using singly linkedlist
  stack_usingLinkedlist.py
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#67 runner_score.py
  runner_score.py
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#64 Hackertoberfest 2022
  addvolumfrendfunc.cpp
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#79 hactoberfest2022
  lallu.cpp
Labels: hacktoberfest-accepted, Hacktoberfest2022

#77 hacktoberfest 2022
  String_slicing.py
Labels: hacktoberfest-accepted

#76 PALINDROME + GRAPH PLOTTING
  COSnSIN.ipynb
  PalindromeNStringReversal.ipynb
Labels: hacktoberfest-accepted

#75 Hacktober 2022
  findd_Factorial.py
Labels: hacktoberfest-accepted

#82 HacktoberFest 2022
  String_demonstration_1.py
Labels: hacktoberfest-accepted

#78 HACKTOBERFEST 2022
  pointer_VEDANT.cpp
Labels: hacktoberfest-accepted

#81 hacktoberfest 2022
  sndkfne.c
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#80 Added basic programs of NumPy
  Time_difference.py
  nparray.py
  npfunction.py
Labels: hacktoberfest-accepted

#74 Live weather notifications for desktop
  .gitignore
  weather_notifications_desktop.py
Labels: hacktoberfest-accepted

#73 added cocktail sorting algorithm in python
  cocktailSort.py
  peigonSort.py
  stoogeSort.py
  timSort.py
Labels: hacktoberfest-accepted

#70 Hacktoberfest 22
  linkedlistinsrt.py
Labels: hacktoberfest-accepted

#69 digit recognizer
  Digit Recognizer.ipynb
Labels: hacktoberfest-accepted

#89 Added python code for Bogo(or permutation) sort, DNF sort and advance linked list
  PythonDSA/BogoSort.py
  PythonDSA/DNF_Sort.py
  PythonDSA/linked_list_advance.py
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#106 hactoberfest2022
  buzz num.cpp
Labels: hacktoberfest-accepted

#111 Hacktoberfest 2022
  cf mainik and array.bin
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#110 added cyclic sort.py
  cyclic sort.java
Labels: hacktoberfest-accepted

#109 Add loop
  loops.py
Labels: hacktoberfest-accepted

#108 Python Decorators
  PythonDecorators.py
Labels: hacktoberfest-accepted

#107 Text repetition N number using python
  Text repetition N number.py
Labels: hacktoberfest-accepted

#100 Hacktoberfest-2022
  radhakrishn.py
Labels: hacktoberfest-accepted

#83 hacktoberfest 2022
  perfect.cpp
Labels: hacktoberfest-accepted

#84 hacktoberfest2022
  check prime or not.cpp
Labels: hacktoberfest-accepted

#113 Hackobterfest-2022
  design.py
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#104 Create euclidGCD.py
  euclidGCD.py
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#103 Create Alarm clock.py
  Alarm clock.py
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#102 added code for python data structure
  pythonprogram.py
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#99 program to find a factorial of given number
  factorial_of _num.py
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#98 Postorder traversal
  fibonacci_numbers.py
  inorder_traversal.py
  postorder_traversal.py
  preorder_traversal.py
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#95 Recursive Function to demonstrate Fibonacci series
  fibonacci_numbers.py
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#91 hacktoberfest22
  PythonDSA/circularque.py
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#88 hactober 2022
  PythonDSA/BinarySearch.py
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#86 Hacktoberfest--2022
  game.py
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022

#85 hactober 2022
  python matrix
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest2022
